### ISSUE TITLE
timer test may be flaky

### ISSUE THREAD

**Issue by wjwwood** [ros2/system_tests#36]
Between two builds of OS X this test failed:

http://ci.ros2.org/job/ros2_batch_ci_osx/194/testReport/junit/(root)/test_time__rmw_connext_dynamic_cpp/timer_during_wait/

The previous build passed that one test.

http://ci.ros2.org/job/ros2_batch_ci_osx/193/

There were small changes which could have affected this, but I think they're unrelated since this only affects one implementation and the changes should have affected both static and dynamic connext if they were the root cause. I don't have time to dig into it right now so I created this issue.

**Comment by jacquelinekay** [comment]
try to fix this week

**Comment by jacquelinekay** [comment]
how ironic, I assigned this to myself but the error only seems to happen intermittently on OSX...

http://ci.ros2.org/view/nightly/job/ros2_batch_ci_osx_nightly/101/
http://ci.ros2.org/view/nightly/job/ros2_batch_ci_osx_nightly/99/

I'm now vnc'd into a Gazebo Jenkins slave because I didn't want to disrupt our Jenkins machine and Steve said it was ok...

there's also a shared_ptr_const_reference test that fails, I can look into that today.

**Comment by dirk-thomas** [comment]
Windows has it too: http://ci.ros2.org/job/ros2_batch_ci_windows/565/testReport/(root)/test_time__rmw_opensplice_cpp/timer_during_wait/
